#!/bin/bash --login
#
#PBS -N test-numpy
#PBS -l select=1
#PBS -l walltime=00:20:00
#PBS -A y07
#PBS -q short

prefix=/work/y07/y07/cse/numpy/1.16.2-python3.6.0-libsci_build1
mkdir -p $prefix/test
(
    cd $prefix/test
    module load python-compute/3.6.0_gcc6.1.0
    module load $HOME/numpy/1.16.2-python3.6.0-libsci_build1/modulefile
    OMP_NUM_THREADS=24 aprun -n 1 -d 24 python3 -c 'import numpy; numpy.test("full")' &> $PBS_O_WORKDIR/test.log
)
